name: juna
description: Plateforme d'abonnement repas pour l'Afrique de l'Ouest.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Environment
  flutter_dotenv: ^5.1.0

  # Animations
  lottie: ^3.1.2

  # Images réseau
  cached_network_image: ^3.3.1

  # Dates
  intl: ^0.20.2

  # Connectivité
  connectivity_plus: ^6.0.3

  # QR Code
  qr_flutter: ^4.1.0

  # Google Fonts
  google_fonts: ^6.2.1

  # HTTP Client
  dio: ^5.4.3

  # Utils
  uuid: ^4.4.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2

  # Image picker (avatar)
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  app_links: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - .env

